# Build speculos-builder and push the resulting docker image to GitHub Packages

name: Speculos Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master
    
jobs:
  build:
    name: Build and push speculos-builder image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push speculos-builder to GitHub Packages
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        dockerfile: build.Dockerfile
        push: true
        registry: ghcr.io
        tags: |
          ghcr.io/blooo-io/speculos-builder:latest
          ghcr.io/blooo-io/speculos-builder:sha-${{ github.sha }}

    - name: Build and push speculos to GitHub Packages
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        dockerfile: Dockerfile
        push: true
        registry: ghcr.io
        tags: |
          ghcr.io/blooo-io/speculos:latest
          ghcr.io/blooo-io/speculos:sha-${{ github.sha }}
